# Generated by Django 4.2.1 on 2023-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_alter_post_author_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/bach_emil.png', upload_to='blog/images'),
        ),
    ]
